# ------------------------------------------------------------
# ansible/playbook/roles/package_docker_setup/tasks/main.yml

---

- name: Import docker common setup role
  ansible.builtin.import_role:
    name: package_docker_common_setup
  vars:
    target: client

- name: Include common vars
  ansible.builtin.include_vars: "{{ playbook_dir }}/roles/package_docker_common_setup/vars/vars.yml"

# ------------------------------------------------------------
# Super user block
- name: Setup docker cilient by super user
  become: true
  become_user: "{{ become_super_user }}"
  # ignore_errors: true
  block:

    # ------------------------------------------------------------
    # RedHat 9 type on super user block
    - name: Setup docker cilient on redhat9 by super user
      when: ansible_distribution_file_variety == "RedHat"
        and ansible_distribution_major_version == "9"
      # ignore_errors: true
      block:

        # ------------------------------------------------------------
        - name: Install docker client
          ansible.builtin.dnf:
            name: "{{ item }}"
            # state: latest
            state: present
          with_items:
            - docker-ce-cli

        # ------------------------------------------------------------
        # End of [RedHat 9 type block]

    # ------------------------------------------------------------
    # End of [Super user block]

# ------------------------------------------------------------
# EOF
