# ------------------------------------------------------------
# ansible/playbook/roles/package.mariadb.server.setup/tasks/main.yml

---
- include_vars: vars.yml

# ------------------------------------------------------------
# Super-user block
- name: Setup mariadb server by super user
  become: true
  become_user: "{{ become_super_user }}"
  # ignore_errors: true
  block:

  # ------------------------------------------------------------
  # RedHat 9 type on super-user block
  - name: Setup mariadb server on redhat9 by super user
    when: ansible_distribution_file_variety == "RedHat"
      and ansible_distribution_major_version == "9"
    # ignore_errors: true
    block:

    # ------------------------------------------------------------
    - name: Install mariadb server
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
      - mariadb-server
      - python3
      - python3-pip
      # - python3-devel
      # - gcc

    # ----------------------------------------------------------
    - name: Install pip for mariadb server
      pip:
        name:
        - PyMySQL
        state: present
        executable: pip3

    # ----------------------------------------------------------
    - name: Start mariadb server
      systemd:
        name: mariadb
        state: started
        # daemon_reload: true
        enabled: true

    # ------------------------------------------------------------
    - name: Setup firewalld for mariadb
      firewalld:
        port: 3306/tcp
        permanent: true
        immediate: true
        state: enabled

    # ----------------------------------------------------------
    - name: Setup character-set-server
      lineinfile:
        dest: "{{ server_conf_path }}"
        insertafter: "{{ server_conf_tag }}"
        line: "character-set-server={{ mariadb_character_set }}"
      notify: Restart mariadb server

    # ----------------------------------------------------------
    - name: Setup default-character-set
      lineinfile:
        dest: "{{ client_conf_path }}"
        insertafter: "{{ client_conf_tag }}"
        line: "default-character-set={{ mariadb_character_set }}"
      notify: Restart mariadb server

    # ------------------------------------------------------------
    # End of [RedHat 9 type block]

  # ----------------------------------------------------------
  - name: Setup root user password
    shell: "mysql -u root mysql -e'SET PASSWORD FOR \"{{ mariadb_root_user }}\"@\"{{ item }}\" = PASSWORD(\"{{ mariadb_root_password }}\");'"
    ignore_errors: true
    with_items:
    - localhost

  # ----------------------------------------------------------
  - name: Setup admin db
    mysql_db:
      login_user: "{{ mariadb_root_user }}"
      login_password: "{{ mariadb_root_password }}"
      # check_implicit_admin: true
      name: "{{ mariadb_admin_db }}"
      state: present

  # ----------------------------------------------------------
  - name: Setup admin user
    mysql_user:
      login_user: "{{ mariadb_root_user }}"
      login_password: "{{ mariadb_root_password }}"
      # check_implicit_admin: true
      name: "{{ mariadb_admin_user }}"
      password: "{{ mariadb_admin_password }}"
      host: "{{ item }}"
      priv: "*.*:ALL,GRANT"
      state: present
    with_items:
    - localhost
    - 127.0.0.1
    - ::1
    - "{{ mariadb_admin_accessable_host }}"

  # ----------------------------------------------------------
  - name: Delete anonymous user
    mysql_user:
      login_user: "{{ mariadb_root_user }}"
      login_password: "{{ mariadb_root_password }}"
      # check_implicit_admin: true
      name: ''
      host_all: true
      state: absent

  # ------------------------------------------------------------
  # End of [Super-user block]

# ------------------------------------------------------------
# EOF
