# ------------------------------------------------------------
# ansible/playbook/roles/package_mongodb_common_setup/tasks/main.yml

---

- name: Include vars
  ansible.builtin.include_vars: vars.yml

# ------------------------------------------------------------
# Super user block
- name: Setup mongodb common by super user
  become: true
  become_user: "{{ become_super_user }}"
  # ignore_errors: true
  block:

    # ------------------------------------------------------------
    # RedHat 9 type on super user block
    - name: Setup mongodb common on redhat9 by super user
      when: ansible_distribution_file_variety == "RedHat"
        and ansible_distribution_major_version == "9"
      # ignore_errors: true
      block:

        # ------------------------------------------------------------
        - name: Setup yum repository mongodb
          ansible.builtin.copy:
            #src: mongodb-org-6.0-redhat9.repo
            src: mongodb-org-6.0-redhat8.repo
            dest: "{{ yum_repo_path_v60_redhat9 }}"
            mode: "0640"

        # ------------------------------------------------------------
        # End of [RedHat 9 type block]

    # ------------------------------------------------------------
    # End of [Super user block]

# ------------------------------------------------------------
# EOF
