# ------------------------------------------------------------
# ansible/playbook/roles/package_redis_server_setup/tasks/main.yml

---

# ------------------------------------------------------------
# EOF
