# ------------------------------------------------------------
# ansible/playbook/roles/package_mongodb_client_setup/tasks/main.yml

---

# ------------------------------------------------------------
# EOF
