# ------------------------------------------------------------
# ansible/playbook/playbook.package.postgresql.setup.yml

---
- hosts: postgresql
  tags: postgresql,postgresql_server
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/common_vars.yml"
  roles:
    - role: package.postgresql.server.setup
      when: setup_rdb is defined
        and setup_rdb == true
        and setup_postgresql_server is defined
        and setup_postgresql_server == true
        and is_rdb_server is defined
        and is_rdb_server == true
        and is_postgresql is defined
        and is_postgresql == true
- hosts: all
  tags: postgresql,postgresql_client
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/common_vars.yml"
  roles:
    - role: package.postgresql.client.setup
      when: setup_rdb is defined
        and setup_rdb == true
        and setup_postgresql_client is defined
        and setup_postgresql_client == true
        and is_rdb_client is defined
        and is_rdb_client == true

# ------------------------------------------------------------
# EOF
