# ------------------------------------------------------------
# ansible/playbook/playbook.package.redis.setup.yml

---
- hosts: redis
  tags: redis,redis_server
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/common_vars.yml"
  roles:
    - role: package.redis.server.setup
      when: setup_cache is defined
        and setup_cache == true
        and setup_redis_server is defined
        and redis_server == true
        and is_cache_server is defined
        and is_cache_server == true
        and is_redis is defined
        and is_redis == true
- hosts: all
  tags: redis,redis_client
  gather_facts: true
  vars_files:
    - "{{ playbook_dir }}/vars/common_vars.yml"
  roles:
    - role: package.redis.client.setup
      when: setup_cache is defined
        and setup_cache == true
        and setup_redis_client is defined
        and redis_client == true
        and is_cache_client is defined
        and is_cache_client == true

# ------------------------------------------------------------
# EOF
