---
- hosts: mariadb
  vars_files:
    - "{{ playbook_dir }}/vars/common_vars.yml"
  roles:
    - role: package.mariadb.server.setup
      when: setup_rdb is defined
        and setup_rdb == true
        and setup_mariadb_server is defined
        and mariadb_server == true
        and is_rdb_server is defined
        and is_rdb_server == true
        and is_mariadb is defined
        and is_mariadb == true
- hosts: all
  vars_files:
    - "{{ playbook_dir }}/vars/common_vars.yml"
  roles:
    - role: package.mariadb.client.setup
      when: setup_rdb is defined
        and setup_rdb == true
        and setup_mariadb_client is defined
        and mariadb_client == true
        and is_rdb_client is defined
        and is_rdb_client == false
