---
- import_playbook: playbook.os.setup.yml
#- import_playbook: os-user.setup.yml
#- import_playbook: mariadb-server.setup.yml
#- import_playbook: mariadb-client.setup.yml
#- import_playbook: postgresql-server.setup.yml
#- import_playbook: postgresql-client.setup.yml
#- import_playbook: mongodb-server.setup.yml
#- import_playbook: mongodb-client.setup.yml
#- import_playbook: redis-server.setup.yml
#- import_playbook: redis-client.setup.yml
#- import_playbook: docker.setup.yml
