version: "3"

# コンテナ
services:
  # [rdb1] MariaDB
  rdb1:
    image: mariadb/server:latest
    container_name: rdb1
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_PASSWORD: 1
      #MYSQL_ROOT_PASSWORD: hogehoge
      MYSQL_USER: admin
      MYSQL_PASSWORD: hogehoge
      MYSQL_DATABASE: mysql
    volumes:
      - /opt/rdb1/mariadb/data:/var/lib/mysql:rw
      - /opt/rdb1/mariadb/log:/var/log/mysql:rw

  # [rdb2] PostgreSQL
  rdb2:
    image: postgres:latest
    container_name: rdb2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hogehoge
    volumes:
      - /opt/rdb2/postgresql/data:/var/lib/postgresql/data:rw
      - /opt/rdb2/postgresql/log:/var/log/postgresql:rw

  # [ddb] MongoDB
  ddb:
    image: mongo:latest
    container_name: ddb
    ports:
      - "27017:27017"
    volumes:
      - /opt/ddb/mongodb/data:/data/db:rw
      - /opt/ddb/mongodb/log:/var/log/mongodb:rw

  # [cache] Redis
  cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - /opt/cache/redis/data:/data:rw

  # [web] Nginx
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - rdb1
      - rdb2
      - ddb
      - cache
    volumes:
      - ./web/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./web/nginx/html:/usr/share/nginx/html:ro
      - /opt/web/nginx/log:/var/log/nginx:rw

  # [web-app] Adminer
  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - rdb1
      - rdb2
      - ddb
