# ------------------------------------------------------------
# ansible/playbook/roles/package_nginx_server_setup/tasks/main.yml

---

# ------------------------------------------------------------
# Super user block
- name: Setup nginx server by super user
  become: true
  become_user: "{{ become_super_user }}"
  # ignore_errors: true
  block:

    # ------------------------------------------------------------
    # RedHat 9 type on super user block
    - name: Setup nginx server on redhat9 by super user
      when: ansible_distribution_file_variety == "RedHat"
        and ansible_distribution_major_version == "9"
      # ignore_errors: true
      block:

        # ------------------------------------------------------------
        - name: Install nginx server
          ansible.builtin.dnf:
            name: "{{ item }}"
            # state: latest
            state: present
          with_items:
            - nginx

        # ----------------------------------------------------------
        - name: Start nginx server
          ansible.builtin.systemd:
            name: nginx
            state: started
            # daemon_reload: true
            enabled: true

        # ------------------------------------------------------------
        - name: Setup firewalld for nginx
          ansible.posix.firewalld:
            service: "{{ item }}"
            permanent: true
            immediate: true
            state: enabled
          with_items:
            - http
            - https

        # ------------------------------------------------------------
        # End of [RedHat 9 type block]

    # ------------------------------------------------------------
    # End of [Super user block]

# ------------------------------------------------------------
# EOF
