# ------------------------------------------------------------
# ansible/playbook/roles/package_postgresql_client_setup/tasks/main.yml

---

# ------------------------------------------------------------
# Super user block
- name: Setup postgresql client by super user
  become: true
  become_user: "{{ become_super_user }}"
  # ignore_errors: true
  block:

    # ------------------------------------------------------------
    # RedHat 9 type on super user block
    - name: Setup postgresql client on redhat9 by super user
      when: ansible_distribution_file_variety == "RedHat"
        and ansible_distribution_major_version == "9"
      # ignore_errors: true
      block:

        # ------------------------------------------------------------
        - name: Install postgresql client
          ansible.builtin.dnf:
            name: "{{ item }}"
            # state: latest
            state: present
          with_items:
            - postgresql

        # ------------------------------------------------------------
        # End of [RedHat 9 type block]

    # ------------------------------------------------------------
    # End of [Super user block]

# ------------------------------------------------------------
# EOF
