---

#------------------------------------------------------------
# RedHat 9 type on super-user block
- name: setup_postgresql_server_on_redhat9_by_super_user
  when: ansible_distribution_file_variety == "RedHat"
    and ansible_distribution_major_version == "9"
  become: true
  become_user: "{{ become_super_user }}"
  #ignore_errors: true
  block:

    #------------------------------------------------------------
    - name: install_postgresql_client
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - postgresql

#------------------------------------------------------------
# EOF
