# ------------------------------------------------------------
# ansible/playbook/roles/package_mongodb_server_setup/handlers/main.yml

---

# ----------------------------------------------------------
- name: Restart mongodb server
  ansible.builtin.include_tasks: "{{ playbook_dir }}/roles/package_mongodb_server_setup/tasks/restart_mongodb_server.yml"

# ------------------------------------------------------------
# EOF
