# ------------------------------------------------------------
# ansible/playbook/roles/package_mongodb_server_setup/tasks/main.yml

---

# ------------------------------------------------------------
# EOF
