# ------------------------------------------------------------
# ansible/playbook/roles/package_mongodb_server_setup/tasks/main.yml

---

- name: Import mongodb common setup role
  ansible.builtin.import_role:
    name: package_mongodb_common_setup
  vars:
    target: server

- name: Include vars
  ansible.builtin.include_vars: vars.yml

# ------------------------------------------------------------
# Super user block
- name: Setup mongodb server by super user
  become: true
  become_user: "{{ become_super_user }}"
  # ignore_errors: true
  block:

    # ------------------------------------------------------------
    # RedHat 9 type on super user block
    - name: Setup mongodb server on redhat9 by super user
      when: ansible_distribution_file_variety == "RedHat"
        and ansible_distribution_major_version == "9"
      # ignore_errors: true
      block:

        # ------------------------------------------------------------
        - name: Install mongodb server
          ansible.builtin.dnf:
            name: "{{ item }}"
            # state: latest
            state: present
          with_items:
            - mongodb-org

        # ----------------------------------------------------------
        - name: Start mongodb server
          ansible.builtin.systemd:
            name: mongod
            state: started
            # daemon_reload: true
            enabled: true

        # ------------------------------------------------------------
        - name: Setup firewalld for mongodb
          ansible.posix.firewalld:
            port: 27017/tcp
            permanent: true
            immediate: true
            state: enabled

        # ----------------------------------------------------------
        - name: Setup bindIp
          ansible.builtin.lineinfile:
            dest: "{{ server_conf_path }}"
            regexp: "^(  )(bindIp:) (127\\.0\\.0\\.1) (.*)$"
            line: |
              \1#\2 \3 \4
              \1\2 ::,0.0.0.0
            backrefs: true
          notify: Restart mongodb server

        # ------------------------------------------------------------
        # End of [RedHat 9 type block]

    # ------------------------------------------------------------
    # End of [Super user block]

# ------------------------------------------------------------
# EOF
