# ------------------------------------------------------------
# ansible/playbook/roles/package_docker_setup/tasks/main.yml

---

- name: Import docker common setup role
  ansible.builtin.import_role:
    name: package_docker_common_setup
  vars:
    target: server

- name: Include common vars
  ansible.builtin.include_vars: "{{ playbook_dir }}/roles/package_docker_common_setup/vars/vars.yml"

- name: Include vars
  ansible.builtin.include_vars: vars.yml

# ------------------------------------------------------------
# Super user block
- name: Setup docker server by super user
  become: true
  become_user: "{{ become_super_user }}"
  # ignore_errors: true
  block:

    # ------------------------------------------------------------
    # RedHat 9 type on super user block
    - name: Setup docker server on redhat9 by super user
      when: ansible_distribution_file_variety == "RedHat"
        and ansible_distribution_major_version == "9"
      # ignore_errors: true
      block:

        # ------------------------------------------------------------
        - name: Install docker server
          ansible.builtin.dnf:
            name: "{{ item }}"
            # state: latest
            state: present
          with_items:
            - docker-ce

        # ----------------------------------------------------------
        - name: Start docker server
          ansible.builtin.systemd:
            name: docker
            state: started
            # daemon_reload: true
            enabled: true

        # ------------------------------------------------------------
        - name: Setup firewalld for docker
          ansible.posix.firewalld:
            port: 2376/tcp
            permanent: true
            immediate: true
            state: enabled

        # ----------------------------------------------------------
        - name: Setup service
          ansible.builtin.lineinfile:
            dest: "{{ service_path }}"
            regexp: "^(ExecStart=.*) (-H fd:\\/\\/) (--containerd=.*)$"
            line: |
              #\1 \2 \3
              \1 \2 --tlsverify --tlscacert={{ docker_cert_path }}/ca.pem --tlscert={{ docker_cert_path }}/server-cert.pem --tlskey={{ docker_cert_path }}/server-key.pem -H tcp://0.0.0.0:2376 \3
            backrefs: true
          notify: Restart docker server

        # ----------------------------------------------------------
        - name: Reload docker server
          ansible.builtin.systemd:
            daemon_reload: true

        # ------------------------------------------------------------
        # End of [RedHat 9 type block]

    # ------------------------------------------------------------
    # End of [Super user block]

# ------------------------------------------------------------
# EOF
