# ------------------------------------------------------------
# ansible/playbook/roles/package_postgresql_server_setup/tasks/restart_postgresql_server.yml

---

# ------------------------------------------------------------
# Super user block
- name: Restart postgresql server by super user
  become: true
  become_user: "{{ become_super_user }}"
  # ignore_errors: true
  block:

    # ------------------------------------------------------------
    # RedHat 9 type
    - name: Restart postgresql server on redhat9 by super user
      when: ansible_distribution_file_variety == "RedHat"
        and ansible_distribution_major_version == "9"
      # ignore_errors: true
      ansible.builtin.systemd:
        name: postgresql
        state: restarted

    # ------------------------------------------------------------
    # End of [Super user block]

# ------------------------------------------------------------
# EOF
