---
- name: print_inventory_info
  debug:
    #var: "{{ item }}"
    msg: "var[{{ item }}]: {{ lookup('vars', item) }}"
  with_items:
    - target_inventory
    - target_env
    - ansible_distribution
    - ansible_distribution_file_variety
    - ansible_distribution_major_version
